require("isaac.options")
require("isaac.keymaps")
require("isaac.plugins")
require("isaac.cmp")
require("isaac.colorscheme")
require("isaac.lsp")
require("isaac.telescope")
require("isaac.treesitter")
require("isaac.treesitter-context")
require("isaac.treesitter-textobjects")
require("isaac.autopairs")
require("isaac.comment")
require("isaac.gitsigns")
require("isaac.nvim-tree")
require("isaac.bufferline")
require("isaac.toggleterm")
require("isaac.iron")
require("isaac.lualine")
require("isaac.trouble")
require("isaac.hop")
require("isaac.glow")
require("isaac.vimwiki")
require("isaac.colorizer")
require("isaac.killerSheep")
require("isaac.surround")
require("isaac.neodev")
-- Fix the br snippet jsx
-- Fix LSP fucking up when split screening jsx and scss
